#!/usr/bin/env python3
"""Publish Hebb skills and agents into .claude/ for Claude Code discovery.

Source of truth stays separated (core vs learned); runtime discovery is unified
via relative symlinks:

    core/skills/[<group>/]<name>/SKILL.md  (core, human-authored) ─┐
    skills/[<group>/]<name>/SKILL.md        (learned, maintainer)   ├─> .claude/skills/<name>
    core/agents/<name>.md                   (core agent defs)       ─┐
    agents/<name>.md                        (learned roles)          ├─> .claude/agents/<name>.md

Skill dirs may be grouped in subfolders (e.g. core/skills/hebb/, common/,
maintainer/) for source-tree organization; the runtime name is the skill dir's
basename, so the grouping is invisible to discovery and names stay flat.

Core shadows learned on a name collision (core is authoritative). Idempotent;
prunes stale symlinks. Run from anywhere; paths are resolved from this file.

Also regenerates the Skills catalog (wiki/skills/index.md) from each published
skill's SKILL.md frontmatter, so the wiki's skills section can never drift from
the published skill set.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # core/tools/ -> hebb/


def rel_symlink(target, linkpath):
    rel = os.path.relpath(target, os.path.dirname(linkpath))
    if os.path.islink(linkpath):
        if os.readlink(linkpath) == rel:
            return "ok"
        os.unlink(linkpath)
    elif os.path.exists(linkpath):
        return f"SKIP (real path exists, not a symlink): {linkpath}"
    os.symlink(rel, linkpath)
    return "linked"


def collect_skills(srcdir):
    """Every skill dir (one holding a SKILL.md) under srcdir, at any depth.

    Skills may be grouped in category subfolders; the key is the skill dir's
    basename. Result is sorted for deterministic publish output.
    """
    found = {}
    for dirpath, dirnames, filenames in os.walk(srcdir):
        if "SKILL.md" in filenames:
            found[os.path.basename(dirpath)] = dirpath
            dirnames[:] = []  # a skill dir is a leaf; don't descend into scripts/ etc.
        else:
            dirnames.sort()  # deterministic traversal order
    return dict(sorted(found.items()))


def collect_agents(srcdir):
    out = {}
    if os.path.isdir(srcdir):
        for name in sorted(os.listdir(srcdir)):
            if name.endswith(".md") and os.path.isfile(os.path.join(srcdir, name)):
                out[name] = os.path.join(srcdir, name)
    return out


def publish(kind, sources, runtime_dir, collector):
    os.makedirs(runtime_dir, exist_ok=True)
    published = {}
    print(f"{kind}s:")
    for label, srcdir in sources:
        for name, path in collector(srcdir).items():
            if name in published:
                print(f"  WARN collision: {kind} '{name}' in '{label}' shadowed by '{published[name][0]}'")
                continue
            published[name] = (label, path)
            print(f"  [{label}] {name}: {rel_symlink(path, os.path.join(runtime_dir, name))}")
    for name in sorted(os.listdir(runtime_dir)):
        link = os.path.join(runtime_dir, name)
        if os.path.islink(link) and name not in published:
            os.unlink(link)
            print(f"  pruned stale: {name}")
    return published


CATALOG_BANNER = ("<!-- GENERATED by core/tools/publish.py from skill frontmatter — "
                  "do not edit by hand. Change a skill's SKILL.md instead. -->")


def parse_frontmatter(path):
    """Minimal YAML-ish frontmatter parser for a SKILL.md: scalars + simple lists.

    Handles `key: value`, inline `key: [a, b]`, and block lists (`key:` then
    indented `- item` lines). Returns {} when there's no frontmatter. No deps.
    """
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return {}
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    meta, cur_key = {}, None
    for line in text[3:end].splitlines():
        if not line.strip():
            continue
        if line.lstrip().startswith("- ") and cur_key:
            meta[cur_key].append(line.lstrip()[2:].strip().strip("'\""))
            continue
        if ":" in line and not line.startswith((" ", "\t")):
            key, _, val = line.partition(":")
            key, val = key.strip(), val.strip()
            if val == "":
                meta[key], cur_key = [], key          # block list follows
            elif val.startswith("[") and val.endswith("]"):
                meta[key] = [v.strip().strip("'\"") for v in val[1:-1].split(",") if v.strip()]
                cur_key = None
            else:
                meta[key], cur_key = val.strip("'\""), None
    return meta


def domain_of(dirpath, root, label):
    """Grouping folder for a skill (e.g. hebb / common / maintainer / a learned domain)."""
    if root:
        parts = os.path.relpath(dirpath, root).split(os.sep)
        if len(parts) >= 2:
            return parts[0]
    return "learned" if label == "learned" else "core"


def write_catalog(published_skills, roots):
    """Regenerate wiki/skills/index.md from the published skills' frontmatter."""
    metas = []
    for name, (label, path) in published_skills.items():
        meta = parse_frontmatter(os.path.join(path, "SKILL.md"))
        req = meta.get("knowledge_required") or []
        opt = meta.get("knowledge_optional") or []
        metas.append({
            "name": meta.get("name", name),
            "description": (meta.get("description") or "").strip(),
            "domain": domain_of(path, roots.get(label, ""), label),
            "required": [req] if isinstance(req, str) else req,
            "optional": [opt] if isinstance(opt, str) else opt,
        })
    by_domain = {}
    for s in metas:
        by_domain.setdefault(s["domain"], []).append(s)
    lines = [
        "# Skills catalog", "", CATALOG_BANNER, "",
        ("The capabilities compiled into Hebb. Each entry names a skill the way Claude Code "
         "loads it (use the named skill rather than re-deriving the capability); follow the "
         "linked wiki pages for the knowledge it builds on. Back to [[index|the wiki index]]."),
        "",
    ]
    for domain in sorted(by_domain):
        lines += [f"## {domain}", ""]
        for s in sorted(by_domain[domain], key=lambda x: x["name"]):
            lines.append(f"- **`{s['name']}`** — {s['description']}")
            if s["required"]:
                lines.append(f"  - required knowledge: {', '.join(s['required'])}")
            if s["optional"]:
                lines.append(f"  - optional knowledge: {', '.join(s['optional'])}")
        lines.append("")
    out = os.path.join(ROOT, "learned", "wiki", "skills", "index.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    print(f"catalog: wrote {os.path.relpath(out, ROOT)} ({len(metas)} skills)")


def main():
    skill_sources = [("core", os.path.join(ROOT, "core", "skills")),
                     ("learned", os.path.join(ROOT, "learned", "skills"))]
    published_skills = publish("skill", skill_sources,
                               os.path.join(ROOT, ".claude", "skills"), collect_skills)
    publish("agent",
            [("core", os.path.join(ROOT, "core", "agents")),
             ("learned", os.path.join(ROOT, "learned", "agents"))],
            os.path.join(ROOT, ".claude", "agents"), collect_agents)
    write_catalog(published_skills, dict(skill_sources))


if __name__ == "__main__":
    main()
